services:
  - type: web
    name: calcula-rendimento-online
    env: docker
    buildCommand: bash backend/build.sh
    startCommand: bash backend/start.sh
    envVars:
      - key: PORT
        value: 8080
